spec-version: 0.30.0
name: dumbrecords
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
- { name: "base", version: '>=4.12 && <4.13' }

ghc-options: -Wall
default-extensions:
- GADTs

- StandaloneDeriving

- ScopedTypeVariables
- RankNTypes
- QuantifiedConstraints

- TypeApplications
- TypeOperators
- MultiParamTypeClasses

- ConstraintKinds
- DataKinds
- PolyKinds
- KindSignatures

- FlexibleInstances
- FlexibleContexts

- UndecidableInstances
- AllowAmbiguousTypes
- OverloadedLabels
- RebindableSyntax
- ImplicitPrelude

library: {}
executable:
  main: Main.hs
